server:
  port: 7070
spring:
  application:
    name: eureke-consumer

eureka:
  instance:
    hostname: eureke-consumer
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}

    #发送心跳给server的频率，每隔这个时间会主动心跳一次
    lease-renewal-interval-in-seconds: 1
    #Server从收到client后，下一次收到心跳的间隔时间。超过这个时间没有接收到心跳EurekaServer就会将这个实例剔除
    lease-expiration-duration-in-seconds: 1

  client:
    healthcheck:
      enabled: true
    service-url:
      defaultZone: http://localhost:8762/eureka/,http://localhost:8763/eureka/
